version: '3'

services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '80:80'
    depends_on:
      - redis
    networks:
      - internal
    volumes:
      - ./nginx/site.conf:/etc/nginx/conf.d/default.conf

  redis:
    image: 'redis:alpine'
    ports:
      - '6379:6379'
    volumes:
      - 'testredis:/data'
    networks:
      - internal

  phpfpm:
    image: 'php:8.1-fpm'
    ports:
      - ':9000'
    volumes:
      - ./:/usr/share/nginx/app
    networks:
      - internal

networks:
  internal:
    driver: bridge

volumes:
  testredis:
    driver: local