version: '3'

services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '443:443'
    depends_on:
      - redis
    networks:
      - internal
    volumes:
      #- ./nginx/amis.conf:/etc/nginx/conf.d/amis.conf
      #- ./nginx/amis.conf:/etc/nginx/conf.d/amis-api.conf
      #- /etc/nginx/sites-available/test-amis:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt

  redis:
    image: 'redis:alpine'
    ports:
      - '6379:6379'
    volumes:
      - 'testredis:/data'
    networks:
      - internal

  phpfpm:
    image: 'php:8.1-fpm'
    ports:
      - '9000:9000'
    volumes:
      - ./:/usr/share/nginx/amis-api
    networks:
      - internal

networks:
  internal:
    driver: bridge

volumes:
  testredis:
    driver: local